# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: default
type: Opaque
data:
  # Example:
  # password: {{ .Values.password | b64enc }}
# stringData:
#   username: admin      # required field for kubernetes.io/basic-auth
#   password: t0p-Secret # required field for kubernetes.io/basic-auth
# immutable: true
---
